import React, { useEffect, useMemo, useState } from 'react';
import { View, Text, ScrollView, StyleSheet, SafeAreaView, TouchableOpacity, TextInput, Alert } from 'react-native';
import { collection, query, orderBy, onSnapshot, addDoc, serverTimestamp, limit } from 'firebase/firestore';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { db } from '../firebase/config';
import { useAuth } from '../firebase/AuthContext';
import { useChild } from '../firebase/ChildContext';
import Card from '../components/Card';
import { spacing, radii, useTheme } from '../theme/colors';

type Entry = { id: string; mood: number; note: string; createdAt: any };

const MOODS = [
  { value: 1, emoji: '😞' },
  { value: 2, emoji: '😕' },
  { value: 3, emoji: '😐' },
  { value: 4, emoji: '🙂' },
  { value: 5, emoji: '😄' },
];

function startOfWeek() {
  const d = new Date();
  const day = d.getDay();
  d.setHours(0, 0, 0, 0);
  d.setDate(d.getDate() - day);
  return d;
}

export default function ProgressJournalScreen() {
  const { colors, typography } = useTheme();
  const { user } = useAuth();
  const { selectedChild } = useChild();
  const [entries, setEntries] = useState<Entry[]>([]);
  const [showForm, setShowForm] = useState(false);
  const [mood, setMood] = useState<number | null>(null);
  const [note, setNote] = useState('');
  const [saving, setSaving] = useState(false);
  const [exporting, setExporting] = useState(false);

  useEffect(() => {
    if (!user || !selectedChild) return;
    const q = query(collection(db, 'users', user.uid, 'children', selectedChild.id, 'journalEntries'), orderBy('createdAt', 'desc'), limit(60));
    const unsubscribe = onSnapshot(q, (snap) => {
      setEntries(snap.docs.map((d) => ({ id: d.id, ...(d.data() as any) })));
    });
    return unsubscribe;
  }, [user, selectedChild]);

  const weekStart = useMemo(() => startOfWeek(), []);
  const entriesThisWeek = entries.filter((e) => e.createdAt?.toDate && e.createdAt.toDate() >= weekStart);

  const avgMoodThisWeek = entriesThisWeek.length
    ? entriesThisWeek.reduce((sum, e) => sum + e.mood, 0) / entriesThisWeek.length
    : null;

  const last7Days = useMemo(() => {
    const days: { label: string; avg: number | null }[] = [];
    for (let i = 6; i >= 0; i--) {
      const d = new Date();
      d.setHours(0, 0, 0, 0);
      d.setDate(d.getDate() - i);
      const next = new Date(d);
      next.setDate(d.getDate() + 1);
      const dayEntries = entries.filter((e) => e.createdAt?.toDate && e.createdAt.toDate() >= d && e.createdAt.toDate() < next);
      const avg = dayEntries.length ? dayEntries.reduce((s, e) => s + e.mood, 0) / dayEntries.length : null;
      days.push({ label: d.toLocaleDateString(undefined, { weekday: 'short' })[0], avg });
    }
    return days;
  }, [entries]);

  const saveEntry = async () => {
    if (!mood) {
      Alert.alert('Pick a mood', "Select how today's gone before saving.");
      return;
    }
    if (!user || !selectedChild) return;
    setSaving(true);
    try {
      await addDoc(collection(db, 'users', user.uid, 'children', selectedChild.id, 'journalEntries'), {
        mood,
        note: note.trim(),
        createdAt: serverTimestamp(),
      });
      setMood(null);
      setNote('');
      setShowForm(false);
    } catch (err: any) {
      Alert.alert('Something went wrong', err.message ?? 'Please try again.');
    } finally {
      setSaving(false);
    }
  };

  const exportPdf = async () => {
    if (!user) return;
    setExporting(true);
    try {
      const childNames = selectedChild?.name || 'your child';

      const rows = entries
        .slice()
        .reverse()
        .map((e) => {
          const date = e.createdAt?.toDate ? e.createdAt.toDate().toLocaleDateString() : '—';
          const emoji = MOODS.find((m) => m.value === e.mood)?.emoji ?? '';
          return `<tr><td>${date}</td><td>${emoji} (${e.mood}/5)</td><td>${e.note || '—'}</td></tr>`;
        })
        .join('');

      const html = `
        <html><body style="font-family: -apple-system, sans-serif; padding: 24px;">
          <h1 style="color:#1F2A44;">Progress Journal — ${childNames}</h1>
          <p style="color:#6B7280;">Generated by Cogniva on ${new Date().toLocaleDateString()}</p>
          <table style="width:100%; border-collapse: collapse; margin-top: 16px;">
            <thead>
              <tr style="text-align:left; border-bottom: 2px solid #E8E9EE;">
                <th style="padding:8px;">Date</th><th style="padding:8px;">Mood</th><th style="padding:8px;">Note</th>
              </tr>
            </thead>
            <tbody>${rows || '<tr><td colspan="3" style="padding:8px;">No entries yet.</td></tr>'}</tbody>
          </table>
        </body></html>
      `;

      const { uri } = await Print.printToFileAsync({ html });
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(uri);
      } else {
        Alert.alert('PDF created', `Saved to: ${uri}`);
      }
    } catch (err: any) {
      Alert.alert('Export failed', err.message ?? 'Please try again.');
    } finally {
      setExporting(false);
    }
  };

  return (
    <SafeAreaView style={[styles.screen, { backgroundColor: colors.bg }]}>
      <ScrollView contentContainerStyle={styles.content}>
        <View style={styles.headerRow}>
          <Text style={typography.display}>Journal</Text>
          <TouchableOpacity style={[styles.addButton, { backgroundColor: colors.ink }]} onPress={() => setShowForm((s) => !s)}>
            <Text style={styles.addButtonText}>{showForm ? 'Cancel' : '+ Log entry'}</Text>
          </TouchableOpacity>
        </View>
        <Text style={[typography.body, { marginBottom: spacing.md }]}>Track wins and challenges over time.</Text>

        {showForm && (
          <Card>
            <Text style={[styles.cardTitle, { color: colors.ink }]}>How's today gone?</Text>
            <View style={styles.moodRow}>
              {MOODS.map((m) => (
                <TouchableOpacity
                  key={m.value}
                  onPress={() => setMood(m.value)}
                  style={[
                    styles.moodButton,
                    { borderColor: colors.border },
                    mood === m.value && { borderColor: colors.primary, backgroundColor: colors.primarySoft },
                  ]}
                >
                  <Text style={{ fontSize: 24 }}>{m.emoji}</Text>
                </TouchableOpacity>
              ))}
            </View>
            <TextInput
              style={[styles.noteInput, { backgroundColor: colors.bg, borderColor: colors.border, color: colors.ink }]}
              placeholder="Anything worth noting? (optional)"
              placeholderTextColor={colors.inkFaint}
              value={note}
              onChangeText={setNote}
              multiline
            />
            <TouchableOpacity style={[styles.saveButton, { backgroundColor: colors.primary }]} onPress={saveEntry} disabled={saving}>
              <Text style={styles.saveButtonText}>{saving ? 'Saving…' : 'Save entry'}</Text>
            </TouchableOpacity>
          </Card>
        )}

        <View style={styles.statRow}>
          <View style={[styles.statBox, { backgroundColor: colors.surface, borderColor: colors.border }]}>
            <Text style={[styles.statNumber, { color: colors.ink }]}>{entriesThisWeek.length}</Text>
            <Text style={[typography.caption, { color: colors.inkFaint }]}>ENTRIES THIS WEEK</Text>
          </View>
          <View style={[styles.statBox, { backgroundColor: colors.surface, borderColor: colors.border }]}>
            <Text style={[styles.statNumber, { color: colors.ink }]}>{avgMoodThisWeek ? avgMoodThisWeek.toFixed(1) : '—'}/5</Text>
            <Text style={[typography.caption, { color: colors.inkFaint }]}>AVG MOOD THIS WEEK</Text>
          </View>
        </View>

        <Card>
          <Text style={[styles.cardTitle, { color: colors.ink }]}>Last 7 days</Text>
          <View style={styles.chartRow}>
            {last7Days.map((d, i) => (
              <View key={i} style={styles.chartBarWrap}>
                <View
                  style={[
                    styles.chartBar,
                    {
                      height: d.avg ? Math.max(8, (d.avg / 5) * 64) : 4,
                      backgroundColor: d.avg ? colors.primary : colors.divider,
                    },
                  ]}
                />
                <Text style={[styles.chartLabel, { color: colors.inkFaint }]}>{d.label}</Text>
              </View>
            ))}
          </View>
        </Card>

        <Card>
          <Text style={[styles.cardTitle, { color: colors.ink }]}>Generate a report</Text>
          <Text style={[typography.body, { color: colors.inkSoft }]}>Export a PDF summary to share with your child's therapist or teacher.</Text>
          <TouchableOpacity style={[styles.exportButton, { backgroundColor: colors.primary }]} onPress={exportPdf} disabled={exporting}>
            <Text style={styles.exportButtonText}>{exporting ? 'Preparing…' : 'Export PDF'}</Text>
          </TouchableOpacity>
        </Card>

        {entries.map((e) => (
          <Card key={e.id}>
            <View style={{ flexDirection: 'row', alignItems: 'center', marginBottom: 4 }}>
              <Text style={{ fontSize: 18, marginRight: 8 }}>{MOODS.find((m) => m.value === e.mood)?.emoji}</Text>
              <Text style={[typography.caption, { color: colors.inkFaint }]}>
                {e.createdAt?.toDate ? e.createdAt.toDate().toLocaleDateString() : ''}
              </Text>
            </View>
            {!!e.note && <Text style={[typography.body, { color: colors.ink }]}>{e.note}</Text>}
          </Card>
        ))}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1 },
  content: { padding: spacing.lg },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  cardTitle: { fontSize: 16, fontWeight: '700', marginBottom: spacing.sm },
  addButton: { borderRadius: radii.pill, paddingVertical: 8, paddingHorizontal: 16 },
  addButtonText: { color: '#fff', fontWeight: '700', fontSize: 13 },
  statRow: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.md },
  statBox: { flex: 1, borderRadius: radii.lg, borderWidth: 1, padding: spacing.md },
  statNumber: { fontSize: 24, fontWeight: '700', marginBottom: 4 },
  exportButton: { alignSelf: 'flex-start', borderRadius: radii.pill, paddingVertical: 8, paddingHorizontal: 18, marginTop: spacing.sm },
  exportButtonText: { color: '#fff', fontWeight: '700', fontSize: 13 },
  moodRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: spacing.sm },
  moodButton: { width: 48, height: 48, borderRadius: 24, borderWidth: 2, alignItems: 'center', justifyContent: 'center' },
  noteInput: { borderWidth: 1, borderRadius: radii.md, padding: spacing.sm, minHeight: 60, marginBottom: spacing.sm },
  saveButton: { borderRadius: radii.pill, paddingVertical: 10, alignItems: 'center' },
  saveButtonText: { color: '#fff', fontWeight: '700', fontSize: 14 },
  chartRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', height: 80 },
  chartBarWrap: { alignItems: 'center', flex: 1 },
  chartBar: { width: 18, borderRadius: 6, marginBottom: 6 },
  chartLabel: { fontSize: 11, fontWeight: '600' },
});
